import { assertEvmAddress } from "../domain/address.js";
import { assertHex } from "../domain/hex.js";
import { CircuitBreaker, ExternalCallError, type FailureKind, withResilience } from "./resilience.js";

export interface JsonRpcError { code: number; message: string; data?: unknown; }
export interface JsonRpcSuccess<T> { jsonrpc: "2.0"; id: number; result: T; }
export interface JsonRpcFailure { jsonrpc: "2.0"; id: number; error: JsonRpcError; }
export type JsonRpcResponse<T> = JsonRpcSuccess<T> | JsonRpcFailure;
export class RpcApplicationRevert extends Error { readonly kind = "application_revert" as const; constructor(message: string, readonly data?: unknown) { super(message); this.name = "RpcApplicationRevert"; } }
export class RpcProviderError extends Error { readonly kind: FailureKind = "provider_failure"; constructor(message: string) { super(message); this.name = "RpcProviderError"; } }
export interface JsonRpcClientOptions { timeoutMs?: number; retry?: { maxAttempts: number; baseDelayMs: number; maxDelayMs: number }; breaker?: { failureThreshold: number; cooldownMs: number }; fetcher?: typeof fetch; }
export interface RpcTransport { request<T>(method: string, params: readonly unknown[]): Promise<T>; getCode(address: string, blockTag?: string): Promise<string>; getStorageAt(address: string, slot: string, blockTag?: string): Promise<string>; call(to: string, data: string, blockTag?: string): Promise<string>; }
function isApplicationRevert(error: JsonRpcError): boolean { if (typeof error.data === "string" && /^0x[0-9a-fA-F]+$/.test(error.data)) return true; return /(?:execution reverted|revert|vm exception|panic)/i.test(error.message); }
function validateRpcResponse<T>(value: unknown): JsonRpcResponse<T> { if (typeof value !== "object" || value === null) throw new RpcProviderError("RPC returned a non-object response"); const response = value as Record<string, unknown>; if (response.jsonrpc !== "2.0" || typeof response.id !== "number") throw new RpcProviderError("Malformed JSON-RPC envelope"); if ("result" in response) return response as unknown as JsonRpcSuccess<T>; if ("error" in response && typeof response.error === "object" && response.error !== null) { const rpcError = response.error as Record<string, unknown>; if (typeof rpcError.code !== "number" || typeof rpcError.message !== "string") throw new RpcProviderError("Malformed JSON-RPC error"); return response as unknown as JsonRpcFailure; } throw new RpcProviderError("Malformed JSON-RPC response: missing result/error"); }
export class JsonRpcClient implements RpcTransport {
  private nextId = 1;
  private readonly breaker: CircuitBreaker;
  private readonly fetcher: typeof fetch;
  private readonly timeoutMs: number;
  private readonly retry: { maxAttempts: number; baseDelayMs: number; maxDelayMs: number };
  constructor(private readonly url: string, options: JsonRpcClientOptions = {}) { if (!/^https?:\/\//i.test(url)) throw new Error("RPC URL must use http or https"); this.timeoutMs = options.timeoutMs ?? 5_000; this.retry = options.retry ?? { maxAttempts: 2, baseDelayMs: 50, maxDelayMs: 500 }; this.breaker = new CircuitBreaker(options.breaker ?? { failureThreshold: 3, cooldownMs: 10_000 }); this.fetcher = options.fetcher ?? fetch; }
  async request<T>(method: string, params: readonly unknown[]): Promise<T> { if (!method || method.length > 128) throw new Error("Invalid JSON-RPC method"); if (params.length > 64) throw new Error("Too many JSON-RPC parameters"); const id = this.nextId++; try { return await withResilience(this.breaker, async (signal) => { const response = await this.fetcher(this.url, { method: "POST", headers: { "content-type": "application/json", accept: "application/json" }, body: JSON.stringify({ jsonrpc: "2.0", id, method, params }), signal }); if (response.status === 429) throw new ExternalCallError({ kind: "rate_limited", message: "RPC provider rate limited the request", retryable: true }); if (!response.ok) throw new ExternalCallError({ kind: "provider_failure", message: `RPC provider returned HTTP ${response.status}`, retryable: response.status >= 500 }); let body: unknown; try { body = await response.json(); } catch { throw new ExternalCallError({ kind: "malformed_response", message: "RPC provider returned invalid JSON", retryable: false }); } const parsed = validateRpcResponse<T>(body); if ("error" in parsed) { if (isApplicationRevert(parsed.error)) throw new RpcApplicationRevert(parsed.error.message, parsed.error.data); throw new RpcProviderError(`JSON-RPC error ${parsed.error.code}: ${parsed.error.message}`); } return parsed.result; }, { timeoutMs: this.timeoutMs, retry: this.retry }, (error) => { if (error instanceof RpcApplicationRevert) return { kind: "application_revert", message: error.message, retryable: false }; if (error instanceof RpcProviderError) return { kind: "provider_failure", message: error.message, retryable: true }; if (error instanceof ExternalCallError) return error.failure; return { kind: "provider_failure", message: error instanceof Error ? error.message : "Unknown RPC failure", retryable: true }; }); } catch (error) { if (error instanceof ExternalCallError && error.failure.kind === "application_revert") throw new RpcApplicationRevert(error.failure.message); throw error; } }
  async getCode(address: string, blockTag = "latest"): Promise<string> { assertEvmAddress(address, "contract address"); validateBlockTag(blockTag); return assertHex(await this.request<string>("eth_getCode", [address, blockTag]), "RPC bytecode"); }
  async getStorageAt(address: string, slot: string, blockTag = "latest"): Promise<string> { assertEvmAddress(address, "storage address"); assertHex(slot, "storage slot"); if (slot.length !== 66) throw new Error("Storage slot must be exactly 32 bytes"); validateBlockTag(blockTag); return assertHex(await this.request<string>("eth_getStorageAt", [address, slot, blockTag]), "RPC storage value"); }
  async call(to: string, data: string, blockTag = "latest"): Promise<string> { assertEvmAddress(to, "call target"); assertHex(data, "call data"); validateBlockTag(blockTag); return assertHex(await this.request<string>("eth_call", [{ to, data }, blockTag]), "RPC call result"); }
}
function validateBlockTag(blockTag: string): void { if (!/^(latest|earliest|pending|safe|finalized)$/.test(blockTag) && !/^0x(?:0|[1-9a-fA-F][0-9a-fA-F]*)$/.test(blockTag)) throw new Error("Invalid block tag"); }
